/**
 * Kod kraju → reprezentatywna strefa IANA (stolica / główna strefa).
 * Używane do wyliczenia „godziny domowej" kierowcy, gdy telefon przestawił się
 * na strefę kraju, w którym aktualnie przebywa. Kraje spoza listy → czas urządzenia.
 */
export const COUNTRY_TIMEZONES: Record<string, string> = {
    PL: 'Europe/Warsaw',
    DE: 'Europe/Berlin',
    LT: 'Europe/Vilnius',
    AT: 'Europe/Vienna',
    BA: 'Europe/Sarajevo',
    BE: 'Europe/Brussels',
    BG: 'Europe/Sofia',
    BY: 'Europe/Minsk',
    CA: 'America/Toronto',
    CH: 'Europe/Zurich',
    CN: 'Asia/Shanghai',
    CZ: 'Europe/Prague',
    CY: 'Asia/Nicosia',
    DK: 'Europe/Copenhagen',
    DZ: 'Africa/Algiers',
    EE: 'Europe/Tallinn',
    ES: 'Europe/Madrid',
    FI: 'Europe/Helsinki',
    FR: 'Europe/Paris',
    GB: 'Europe/London',
    GR: 'Europe/Athens',
    HR: 'Europe/Zagreb',
    HU: 'Europe/Budapest',
    IT: 'Europe/Rome',
    KZ: 'Asia/Almaty',
    LU: 'Europe/Luxembourg',
    LV: 'Europe/Riga',
    MA: 'Africa/Casablanca',
    MC: 'Europe/Monaco',
    MD: 'Europe/Chisinau',
    ME: 'Europe/Podgorica',
    MK: 'Europe/Skopje',
    MN: 'Asia/Ulaanbaatar',
    NL: 'Europe/Amsterdam',
    NO: 'Europe/Oslo',
    PT: 'Europe/Lisbon',
    RO: 'Europe/Bucharest',
    RS: 'Europe/Belgrade',
    RU: 'Europe/Moscow',
    SE: 'Europe/Stockholm',
    SK: 'Europe/Bratislava',
    TR: 'Europe/Istanbul',
    UA: 'Europe/Kyiv',
    US: 'America/New_York',
    XK: 'Europe/Belgrade',
};
