export type ActivitiesTypes =
  | 'tourStart'
  | 'tourStop'
  | 'dayStart'
  | 'dayStop'
  | 'borderCross'
  | 'anotherLog'
  | 'attachTrailer'
  | 'detachTrailer'
  | 'loadingArrival'
  | 'unloadingArrival'
  | 'loadingCompleted'
  | 'unloadingCompleted'
  | 'addExpense'
  | 'addFuelRefuel'
  | 'addDefRefuel'
  | 'addService'
  | 'addLubrication';
