export interface GeneralFormData {
  date: string;
  truck: string;
  trailer: string;
  vehicle: string;
  odometer: string;
  action: string;
  fuelQuantity: string;
  fuelCombustion: string;
  place: string;
  placeId: string;
  country: string;
  senderId: string;
  receiverId: string;
  notes: string;
  doubleCrew: 'false' | 'true';
  cardInserted: 'false' | 'true';
  cardTakeOut: 'false' | 'true';
  driveTime: string;
  driveTime2: string;
  breakTaken: string;
  breakDriveTime: string;
  breakOnlyBreak: 'false' | 'true';
  breakChangeToSlot1: 'false' | 'true';
  breakMyCardInSlot1: 'false' | 'true';
  addNewBorder: 'false' | 'true';
  description: string;
  quantity: string;
  weight: string;
  reference: string;
  loadId: string;
  payment: string;
  expenseQuantity: string;
  expenseUnitPrice: string;
  expenseItemDescription: string;
  expenseAmount: string;
  expenseCurrency: string;
  expenseForeignAmount: string;
  expenseForeignCurrency: string;
  serviceVehicleId: string;
  serviceVehicleReg: string;
  serviceType: string;
  serviceEntry: string;
  serviceVehicleType: string;
}
