import { CommonInterface } from "@/types";

export const common: CommonInterface = {
    en: {
        appName: `Driver's Log Book`,
        homePageTitle: 'Home',
        dayStartPageTitle: 'Start working day',
        dayStopPageTitle: 'Finish working day',
        borderCrossPageTitle: 'Border cross',
        logAddPageTitle: 'Add other activity',
        infoPageTitle: 'Info',
        routesPageTitle: 'Routes',
        placesPageTitle: 'Places',
        vehiclesPageTitle: 'Vehicles',
        profilePageTitle: 'Profile',
        notFoundPageTitle: 'Ooops :( You got Lost.',
        goToMainPage: 'Go to main page',
        logIn: 'Log in',
        register: `If you don't have an account - click here.`,
        email: 'Email',
        password: 'Password',
    },
    pl: {
        appName: 'Dziennik kierowcy',
        homePageTitle: 'Strona główna',
        dayStartPageTitle: 'Rozpocznij dzień pracy',
        dayStopPageTitle: 'Zakończ dzień pracy',
        borderCrossPageTitle: 'Przekroczenie granicy',
        logAddPageTitle: 'Dodaj inną czynność',
        infoPageTitle: 'Info',
        routesPageTitle: 'Trasy',
        placesPageTitle: 'Adresy',
        vehiclesPageTitle: 'Pojazdy',
        profilePageTitle: 'Profil',
        notFoundPageTitle: 'Ooops :( Zabłądziłeś.',
        goToMainPage: 'Wróć do ekranu startowego',
        logIn: 'Zaloguj',
        register: 'Jeśli nie masz u nas konta - kliknij tutaj.',
        email: 'Email',
        password: 'Hasło',
    }
}