import { CommonInterface } from "@/types";

export const common: CommonInterface = {
    en: {
        appName: `Driver's Log Book`,
        homePageTitle: 'Home',
        infoPageTitle: 'Info',
        routesPageTitle: 'Routes',
        placesPageTitle: 'Places',
        vehiclesPageTitle: 'Vehicles',
        profilePageTitle: 'Profile',
        notFoundPageTitle: 'Ooops :( You got Lost.',
        registerPageTitle: 'Create new Account',
        goToMainPage: 'Go to main page',
        logIn: 'Log in',
        register: `If you don't have an account - click here.`,
        email: 'Email',
        emailHelper: 'The entered email is in an invalid format.',
        password: 'Password',
        passwordHelper: 'The password must be at least 8 characters long and must contain at least one uppercase letter, at least one digit, and at least one special character.',
        language: 'Language',
        companyName: 'Company Name',
        companyNameHelper: 'The company name cannot exceed 30 characters.',
        city: 'City',
        cityHelper: 'The name of the city cannot exceed 30 characters.',
        code: 'Post Code',
        codeHelper: 'The post code cannot exceed 10 characters.',
        country: 'Country',
        street: 'Street',
        streetHelper: 'The name of the street cannot exceed 50 characters.',
        defaultCustomer: 'Default Customer',
        defaultCustomerHelper: 'The name of the default customer cannot exceed 20 characters.',
        firstName: 'First Name',
        firstNameHelper: 'The first name cannot exceed 22 characters.',
        lastName: 'Last Name',
        lastNameHelper: 'The last name cannot exceed 22 characters.',
        search: 'Search',
        companyDetails: 'Company Details',
        loginDetails: 'Login Details',
        additionalData: 'Additional Data',
        additionalDataDescription: 'The data below is used for additional functions, they are not required. You will be able to edit them later.',
        createAccount: 'Create New Account',
        amount: 'Amount',
        salaryAmount: 'Salary amount',
        currency: 'Currency',
        chooseFromList: 'Choose from the list:',
        bidType: 'Type of remuneration',
        bidType0: 'not specified',
        bidType1: 'per day',
        bidType2: 'per km',
        bidType3: 'fixed',
        registerSuccess: 'Account has been successfully created! You can now log in.',
        dateTime: 'Date',
        odometer: 'Odometer',
        odometerHelper: 'Mileage since last activity',
        place: 'Place',
        placeHelper: 'The place name cannot exceed 30 characters.',
        choosePlace: 'Choose place',
        placeType: 'Group',
        placeType0: 'Other',
        placeType1: 'Transport Company (base)',
        placeType2: 'Loading place',
        placeType3: 'Unloading place',
        placeType4: 'Loading&Unloading place',
        placeType5: 'Parking',
        placeType6: 'Workshop/Dealer',
        placeType7: 'Customs',
        placeTypeAll: 'All',
        favorite: 'Favourite',
        activity: 'Activity log name',
        activityHelper: 'The activity log name cannot exceed 100 characters.',
        notes: 'Notes',
        confirmation: 'Confirmation',
        confirmationDeleteElement: (x) => `Are you sure you want to delete ${x}?`,
        cancel: 'Cancel',
        delete: 'Delete',
        doubleCrew: 'Double crew',
        insertedCard: 'Driver card inserted',
        cardTakeOut: 'I take out my driver card',
        no: 'No',
        yes: 'Yes',
        driveTime: 'Drive time',
        driveTime2: '2nd driver drive time',
        driveTimeHelper: 'Type your driving time from tacho throughout the day.',
        driveTimeHelper2: 'You can also enter the co-driver driving time.',
        fuelCombustion: 'Amount of fuel consumed',
        fuelQuantity: 'Fuel level',
        truck: 'Truck reg. plate',
        trailer: 'Trailer reg. plate',
        vehicleInput: 'Vehicle',
    },
    pl: {
        appName: 'Dziennik kierowcy',
        homePageTitle: 'Strona główna',
        infoPageTitle: 'Info',
        routesPageTitle: 'Trasy',
        placesPageTitle: 'Adresy',
        vehiclesPageTitle: 'Pojazdy',
        profilePageTitle: 'Profil',
        notFoundPageTitle: 'Ooops :( Zabłądziłeś.',
        registerPageTitle: 'Stwórz nowe konto',
        goToMainPage: 'Wróć do ekranu startowego',
        logIn: 'Zaloguj',
        register: 'Jeśli nie masz u nas konta - kliknij tutaj.',
        email: 'Email',
        emailHelper: 'Wpisany e-mail ma nieprawidłowy format.',
        password: 'Hasło',
        passwordHelper: 'Hasło musi mieć min. 8 znaków i musi zawierać przynajmniej jedną dużą literę, conajmniej jedną cyfrę oraz conajmniej jeden znak specjalny.',
        language: 'Język',
        companyName: 'Nazwa firmy',
        companyNameHelper: 'Nazwa firmy nie może przekraczać 30 znaków.',
        city: 'Miejscowość',
        cityHelper: 'Nazwa miasta nie może przekraczać 30 znaków.',
        code: 'Kod pocztowy',
        codeHelper: 'Kod pocztowy nie może być dłuższy niż 10 znaków.',
        country: 'Kraj',
        street: 'Ulica',
        streetHelper: 'Nazwa ulicy nie może przekraczać 50 znaków.',
        defaultCustomer: 'Domyślny zleceniodawca',
        defaultCustomerHelper: 'Nazwa domyślnego zleceniodawcy nie może przekraczać 20 znaków.',
        firstName: 'Imię',
        firstNameHelper: 'Imię nie może przekraczać 22 znaków.',
        lastName: 'Nazwisko',
        lastNameHelper: 'Nazwisko nie może przekraczać 22 znaków.',
        search: 'Szukaj',
        companyDetails: 'Dane firmy',
        loginDetails: 'Dane logowania',
        additionalData: 'Dodatkowe informacje',
        additionalDataDescription: 'Dane poniżej są wykorzystywane do dodatkowych funkcji, jednak nie są wymagane. Będziesz mógł je edytować później.',
        createAccount: 'Utwórz nowe konto',
        amount: 'Kwota',
        salaryAmount: 'Kwota wynagrodzenia',
        currency: 'Waluta',
        chooseFromList: 'Wybierz z listy:',
        bidType: 'Rodzaj wynagrodzenia',
        bidType0: 'nie wybrano',
        bidType1: 'dniówka',
        bidType2: 'za km',
        bidType3: 'stałe',
        registerSuccess: 'Konto zostało utworzone pomyślnie! Teraz możesz się zalogować.',
        dateTime: 'Data',
        odometer: 'Stan licznika',
        odometerHelper: 'Przebieg od ostatniej czynności',
        place: 'Miejsce',
        placeHelper: 'Nazwa miejsca nie może przekraczać 30 znaków.',
        choosePlace: 'Wybierz miejsce',
        placeType: 'Grupa',
        placeType0: 'Inne',
        placeType1: 'Firma transportowa (baza)',
        placeType2: 'Miejsce załadunku',
        placeType3: 'Miejsce rozładunku',
        placeType4: 'Załadunek i Rozładunek',
        placeType5: 'Parking',
        placeType6: 'Warsztat/Serwis',
        placeType7: 'Urząd/Agencja celna',
        placeTypeAll: 'Wszystkie',
        favorite: 'Ulubione',
        activity: 'Czynność',
        activityHelper: 'Nazwa czynności nie może przekraczać 100 znaków.',
        notes: 'Notatki',
        confirmation: 'Potwierdzenie',
        confirmationDeleteElement: (x) => `Czy na pewno chcesz usunąć ${x} ?`,
        cancel: 'Anuluj',
        delete: 'Usuń',
        doubleCrew: 'Podwójna obsada',
        insertedCard: 'Włożono kartę kierowcy',
        cardTakeOut: 'Wyciągam kartę kierowcy',
        no: 'Nie',
        yes: 'Tak',
        driveTime: 'Czas jazdy',
        driveTime2: 'Czas jazdy 2 kierowcy',
        driveTimeHelper: 'Spisz swój czas jazdy z tachografu z całego dnia.',
        driveTimeHelper2: 'Możesz też wpisać czas jazdy zmiennika celem lepszego zliczania statystyk.',
        fuelQuantity: 'Poziom paliwa',
        fuelCombustion: 'Ilość spalonego paliwa',
        truck: 'Nr. rej. ciężarówki',
        trailer: 'Nr. rej. naczepy/przyczepy',
        vehicleInput: 'Pojazd',
    }
}