import { CommonInterface } from "@/types";

export const common: CommonInterface = {
    en: {
        appName: `Driver's Log Book`,
        homePageTitle: 'Home',
        infoPageTitle: 'Info',
        routesPageTitle: 'Routes',
        placesPageTitle: 'Places',
        vehiclesPageTitle: 'Vehicles',
        profilePageTitle: 'Profile',
        notFoundPageTitle: 'Ooops :( You got Lost.',
        registerPageTitle: 'Create new Account',
        goToMainPage: 'Go to main page',
        logIn: 'Log in',
        register: `If you don't have an account - click here.`,
        email: 'Email',
        emailHelper: 'The entered email is in an invalid format.',
        password: 'Password',
        passwordHelper: 'The password must be at least 8 characters long and must contain at least one uppercase letter, at least one digit, and at least one special character.',
        language: 'Language',
        companyName: 'Company Name',
        companyNameHelper: 'The company name cannot exceed 30 characters.',
        city: 'City',
        cityHelper: 'The name of the city cannot exceed 30 characters.',
        code: 'Post Code',
        codeHelper: 'The post code cannot exceed 10 characters.',
        country: 'Country',
        street: 'Street',
        streetHelper: 'The name of the street cannot exceed 50 characters.',
        defaultCustomer: 'Default Customer',
        defaultCustomerHelper: 'The name of the default customer cannot exceed 20 characters.',
        firstName: 'First Name',
        firstNameHelper: 'The first name cannot exceed 22 characters.',
        lastName: 'Last Name',
        lastNameHelper: 'The last name cannot exceed 22 characters.',
        search: 'Search',
        companyDetails: 'Company Details',
        loginDetails: 'Login Details',
        additionalData: 'Additional Data',
        additionalDataDescription: 'The data below is used for additional functions, they are not required. You will be able to edit them later.',
        createAccount: 'Create New Account',
        amount: 'Amount',
        salaryAmount: 'Salary amount',
        currency: 'Currency',
        chooseFromList: 'Choose from the list:',
        bidType: 'Type of remuneration',
        bidType0: 'not specified',
        bidType1: 'per day',
        bidType2: 'per km',
        bidType3: 'fixed',
        registerSuccess: 'Account has been successfully created! You can now log in.',
    },
    pl: {
        appName: 'Dziennik kierowcy',
        homePageTitle: 'Strona główna',
        infoPageTitle: 'Info',
        routesPageTitle: 'Trasy',
        placesPageTitle: 'Adresy',
        vehiclesPageTitle: 'Pojazdy',
        profilePageTitle: 'Profil',
        notFoundPageTitle: 'Ooops :( Zabłądziłeś.',
        registerPageTitle: 'Stwórz nowe konto',
        goToMainPage: 'Wróć do ekranu startowego',
        logIn: 'Zaloguj',
        register: 'Jeśli nie masz u nas konta - kliknij tutaj.',
        email: 'Email',
        emailHelper: 'Wpisany e-mail ma nieprawidłowy format.',
        password: 'Hasło',
        passwordHelper: 'Hasło musi mieć min. 8 znaków i musi zawierać przynajmniej jedną dużą literę, conajmniej jedną cyfrę oraz conajmniej jeden znak specjalny.',
        language: 'Język',
        companyName: 'Nazwa firmy',
        companyNameHelper: 'Nazwa firmy nie może przekraczać 30 znaków.',
        city: 'Miejscowość',
        cityHelper: 'Nazwa miasta nie może przekraczać 30 znaków.',
        code: 'Kod pocztowy',
        codeHelper: 'Kod pocztowy nie może być dłuższy niż 10 znaków.',
        country: 'Kraj',
        street: 'Ulica',
        streetHelper: 'Nazwa ulicy nie może przekraczać 50 znaków.',
        defaultCustomer: 'Domyślny zleceniodawca',
        defaultCustomerHelper: 'Nazwa domyślnego zleceniodawcy nie może przekraczać 20 znaków.',
        firstName: 'Imię',
        firstNameHelper: 'Imię nie może przekraczać 22 znaków.',
        lastName: 'Nazwisko',
        lastNameHelper: 'Nazwisko nie może przekraczać 22 znaków.',
        search: 'Szukaj',
        companyDetails: 'Dane firmy',
        loginDetails: 'Dane logowania',
        additionalData: 'Dodatkowe informacje',
        additionalDataDescription: 'Dane poniżej są wykorzystywane do dodatkowych funkcji, jednak nie są wymagane. Będziesz mógł je edytować później.',
        createAccount: 'Utwórz nowe konto',
        amount: 'Kwota',
        salaryAmount: 'Kwota wynagrodzenia',
        currency: 'Waluta',
        chooseFromList: 'Wybierz z listy:',
        bidType: 'Rodzaj wynagrodzenia',
        bidType0: 'nie wybrano',
        bidType1: 'dniówka',
        bidType2: 'za km',
        bidType3: 'stałe',
        registerSuccess: 'Konto zostało utworzone pomyślnie! Teraz możesz się zalogować.',
    }
}