import { CountriesInterface } from "@/types";

export const countries: CountriesInterface = {
    en: {
        PL: 'Poland',
        DE: 'Germany',
        LT: 'Lithuania',
        AT: 'Austria',
        BA: 'Bosnia and Herzegovina',
        BE: 'Belgium',
        BG: 'Bulgaria',
        BY: 'Belarus',
        CA: 'Canada',
        CH: 'Switzerland',
        CN: 'China',
        CZ: 'Czech Republic',
        CY: 'Cyprus',
        DK: 'Denmark',
        DZ: 'Algeria',
        EE: 'Estonia',
        ES: 'Spain',
        FI: 'Finland',
        FR: 'France',
        GB: 'United Kingdom',
        GR: 'Greece',
        HR: 'Croatia',
        HU: 'Hungary',
        IT: 'Italy',
        KZ: 'Kazakhstan',
        LU: 'Luxembourg',
        LV: 'Latvia',
        MA: 'Morocco',
        MC: 'Monaco',
        MD: 'Moldova',
        ME: 'Montenegro',
        MK: 'Macedonia',
        MN: 'Mongolia',
        NL: 'Netherlands',
        NO: 'Norway',
        PT: 'Portugal',
        RO: 'Romania',
        RS: 'Serbia',
        RU: 'Russian Federation',
        SE: 'Sweden',
        SK: 'Slovakia',
        TR: 'Turkey',
        UA: 'Ukraine',
        US: 'USA',
        XK: 'Kosovo',
    },
    pl: {
        PL: 'Polska',
        DE: 'Niemcy',
        LT: 'Litwa',
        AT: 'Austria',
        BA: 'Bośnia i Chercegowina',
        BE: 'Belgia',
        BG: 'Bułgaria',
        BY: 'Białoruś',
        CA: 'Kanada',
        CH: 'Szwajcaria',
        CN: 'Chiny',
        CZ: 'Czechy',
        CY: 'Cypr',
        DK: 'Dania',
        DZ: 'Algeria',
        EE: 'Estonia',
        ES: 'Hiszpania',
        FI: 'Finlandia',
        FR: 'Francja',
        GB: 'Wielka Brytania',
        GR: 'Grecja',
        HR: 'Chorwacja',
        HU: 'Węgry',
        IT: 'Włochy',
        KZ: 'Kazachstan',
        LU: 'Luksemburg',
        LV: 'Łotwa',
        MA: 'Maroko',
        MC: 'Monaco',
        MD: 'Mołdawia',
        ME: 'Czarnogóra',
        MK: 'Macedonia',
        MN: 'Mongolia',
        NL: 'Holandia',
        NO: 'Norwegia',
        PT: 'Portugalia',
        RO: 'Rumunia',
        RS: 'Serbia',
        RU: 'Rosja',
        SE: 'Szwecja',
        SK: 'Słowacja',
        TR: 'Turcja',
        UA: 'Ukraina',
        US: 'USA',
        XK: 'Kosovo',
    },
}