import { DtcErrorsInterface } from "@/types/text/DtcErrorsInterface";

export const dtcErrors: DtcErrorsInterface = {
    en: {
        invalidLoginData: 'Incorrect login details.',
        country: 'Please select country.',
        noActiveRoute: `You don't have a route to record this activity.`,
        activeRoute: 'You have already started a route, so you cannot start a new one.',
        registerResInvEmail: 'You have entered an incorrect e-mail address format.',
        registerResEmailExist: 'The e-mail address you entered already exists. If this is your e-mail - please contact the administrator.',
        actionNoExist: 'Please top up the activity field.',
        registerResInvPassword: 'You have entered an incorrect password format.',
        registerCompanyNameNotExist: 'Please enter the company name.',
        registerCompanyCityNotExist: 'Please enter the company city.',
        trailerExist: 'You have already entered the connected trailer.',
        noTrailer: `You don't have a trailer attached that you could unhook.`,
        countryConflict: 'The country entered is the same as the one you are currently in. You must provide the country you are entering.',
        dayExist: `You've already started your working day, so you can\'t start the next one until you finish it.`,
        dayExistRegardRoute: 'You cannot finish your route until you finish your current working day.',
        noVehicle: 'You must select a loaded vehicle.',
        truckNoExist: 'Please enter truck number.',
        noWeight: 'You must enter the weight of the load.',
        noDescription: 'You must enter the description of the load.',
        typeFuelBurned: 'You forgot to top up the amount of fuel burned.',
        dayNotExist: `You don't have a working day that you could finish.`,
        noLoadChosen: 'Please choose the load.',
        chosenLoadIsUnloaded: 'The selected load is already unloaded.',
        noLoadReceiver: 'You cannot enter a receiver as unloading place because the selected load does not have any receiver.',
        noExpenseDescription: 'You must enter a description of the expense (item).',
        addVehicleRegEmpty: `You must enter your vehicle's registration number.`,
        addVehicleWeightEmpty: `You must enter the vehicle's curb weight.`,
        vehicleRegExist: 'You already have a vehicle with this registration number.',
        chooseServicedVehicle: 'The vehicle for service/service has not been selected.',
        noServiceEntry: 'No operation/service activity has been entered.',
        youHaveToChooseRoutes: 'You must select at least one route for settlement.',
        monthIncorrectFormat: 'The wrong settlement period format was entered.',
        cannotEditSettledTourData: 'You cannot edit data assigned to a route that has already been settled.',
        apiUnauthorized: 'You do not have access to this part of the application. Please contact the administrator.',
        apiUnknownError: 'An unknown error occurred. Please contact the administrator.',
        apiConnectionError: 'The server is not responding. Please check your internet connection.',
    },
    pl: {
        invalidLoginData: 'Podano niepoprawne dane użytkownika.',
        country: 'Nie wybrałeś kraju.',
        noActiveRoute: 'Nie masz rozpoczętej trasy w której mógłbyś wykonać tą czynność.',
        activeRoute: 'Masz już rozpoczętą trasę, więc nie możesz rozpocząć kolejnej.',
        registerResInvEmail: 'Podałeś niepoprawny format adresu e-mail.',
        registerResEmailExist: 'Podany adres e-mail już istnieje. Jeżeli masz problem z logowaniem - skontaktuj się z administratorem.',
        actionNoExist: 'Uzupełnij czynność którą chcesz wpisać.',
        registerResInvPassword: 'Podałeś niepoprawny format hasła.',
        registerCompanyNameNotExist: 'Musisz wpisać nazwę firmy.',
        registerCompanyCityNotExist: 'Musisz wpisać nazwę miejsowości siedziby firmy.',
        trailerExist: 'Masz już wpisaną podpiętą przyczepę.',
        noTrailer: 'Nie masz żadnej podpiętej naczepy do odpięcia.',
        countryConflict: 'Podany kraj jest taki sam jak ten w którym się obecnie znajdujesz. Musisz podać kraj do którego wjeżdzasz.',
        dayExist: 'Masz już rozpoczęty dzień pracy, więc nie możesz zacząć kolejnego do póki go nie zakończysz.',
        dayExistRegardRoute: 'Nie możesz zakończyć trasy do póki nie zakończysz obecnego dnia pracy.',
        noVehicle: 'Musisz wybrać załadowany pojazd.',
        truckNoExist: 'Podaj nr. rej. ciężarówki.',
        noWeight: 'Musisz podać masę ładunku.',
        noDescription: 'Musisz podać opis towaru.',
        typeFuelBurned: 'Zapomniałeś uzupełnić ilośći spalonego paliwa.',
        dayNotExist: 'Nie masz rozpoczętego dnia pracy który mógłbyś zakończyć.',
        noLoadChosen: 'Nie wybrano ładunku.',
        chosenLoadIsUnloaded: 'Wybrany ładunek jest już rozładowany.',
        noLoadReceiver: 'Nie można wpisać odbiorcy gdyż wybrany ładunek go nie posiada.',
        noExpenseDescription: 'Musisz wpisać opis wydatku (pozycję).',
        addVehicleRegEmpty: 'Musisz podać numer rejestracyjny pojazdu.',
        addVehicleWeightEmpty: 'Musisz podać masę własną dodawanego pojazdu.',
        vehicleRegExist: 'Masz już pojazd o tym numerze rejestracyjnym.',
        chooseServicedVehicle: 'Nie wybrano pojazdu którego ma dotyczyć obsługa/serwis.',
        noServiceEntry: 'Nie wpisano żadnej czynności obsługi/serwisu.',
        youHaveToChooseRoutes: 'Musisz wybrać conajmniej jedną trasę do rozliczenia.',
        monthIncorrectFormat: 'Podano zły format okresu rozliczenia.',
        cannotEditSettledTourData: 'Nie możesz edytować danych przypisanych do rozliczonej już trasy.',
        apiUnauthorized: 'Nie masz dostępu do tej części aplikacji. Skontaktuj się z administratorem.',
        apiUnknownError: 'Wystąpił nieznany błąd. Skontaktuj się z administratorem.',
        apiConnectionError: 'Serwer nie odpowiada. Sprawdź swoje połączenie.'
    }
}