import { FriendsInterface } from "@/types/text/FriendsInterface";

// Odpowiednik front `assets/txt/friends.ts` (warstwa znajomych na mapie miejsc).
export const friends: FriendsInterface = {
    en: {
        friendsToggleLabel: 'Friends',
        friendsTab: 'Friends',
        outgoingRequestsHeader: 'Sent invitations',
        cancelInvite: 'Cancel invitation',
        noFriends: 'You have no friends added yet.',
        placesToggleLabel: 'Places',
        selfLabel: 'You',
        addFriend: 'Add a friend',
        addFriendConsentInfo: "After your friend accepts the invitation, you will both be able to see each other's last known position and information about the destination of the load currently being transported.",
        email: 'E-mail',
        inviteSubmit: 'Send invitation',
        inviteSuccess: 'Invitation sent successfully.',
        incomingRequestsHeader: 'Pending invitations',
        accept: 'Accept',
        decline: 'Decline',
        removeFriend: 'Remove friend',
        removeFriendConfirm: (x) => `Are you sure you want to remove ${x} from your friends? You will both lose access to each other's position and cargo destination.`,
        lastPositionLabel: 'Last position',
        currentCargoLabel: 'Destination',
        targetPlaceLabel: 'Travel destination',
        loadDestinationsLabel: 'Cargo destination(s)',
        noActiveTour: 'No destination or active tour',
        noPosition: 'Position not known yet',
    },
    pl: {
        friendsToggleLabel: 'Znajomi',
        friendsTab: 'Znajomi',
        outgoingRequestsHeader: 'Wysłane zaproszenia',
        cancelInvite: 'Anuluj zaproszenie',
        noFriends: 'Nie masz jeszcze dodanych znajomych.',
        placesToggleLabel: 'Miejsca',
        selfLabel: 'Ty',
        addFriend: 'Dodaj znajomego',
        addFriendConsentInfo: 'Po zaakceptowaniu zaproszenia przez znajomego będziecie nawzajem mieli dostęp do swojej ostatniej pozycji oraz informacji o celu podróży i miejscach docelowych aktualnie przewożonego ładunku.',
        email: 'E-mail',
        inviteSubmit: 'Wyślij zaproszenie',
        inviteSuccess: 'Zaproszenie zostało wysłane.',
        incomingRequestsHeader: 'Oczekujące zaproszenia',
        accept: 'Akceptuj',
        decline: 'Odrzuć',
        removeFriend: 'Usuń znajomego',
        removeFriendConfirm: (x) => `Czy na pewno chcesz usunąć ${x} ze znajomych? Oboje stracicie dostęp do swojej pozycji i celu ładunku.`,
        lastPositionLabel: 'Ostatnia pozycja',
        currentCargoLabel: 'Cel',
        targetPlaceLabel: 'Cel podróży',
        loadDestinationsLabel: 'Miejsca docelowe ładunku',
        noActiveTour: 'Brak celu i aktywnej trasy',
        noPosition: 'Pozycja jeszcze nieznana',
    },
};
