import { HomeInterface } from "@/types/text/HomeInterface";

export const home: HomeInterface = {
    en: {
        blockedDescription: `Your account is inactive. If you wish to activate it and gain full access to the application's features, please contact the Administrator.`,
        dayStart: 'Start working day',
        dayStop: 'Finish working day',
        dayExist: `You've already started your working day, so you can't start the next one until you finish it.`,
        dayNotExist: 'You don\'t have a working day that you could finish.',
        crossBorder: 'Border cross',
        crossBorderSwitchToAdd: 'Add new border crossing',
        crossBorderSwitchToChoose: 'Choose border crossing',
        border: 'Border',
        crossBorderYouAre: (x) => `You are now in ${x}. Select the country you want to enter:`,
        addLog: 'Add other activity',
        addLogSuccess: (x) => `Activity added: ${x}.`,
        adblueRefuel: 'Adblue(Def) refueling',
        dieselRefuel: 'Diesel refueling',
        addExpense: 'Add expence',
        startedDayAction: 'Starting the day',
        startedDayActionCardInsert: '(card insert)',
        finishedDayAction: 'End of the day',
        finishedDayActionCardTakeOut: '(card take out)',
        expenseItemDescription: 'Item (expense description)',
        expenseItemDescriptionHelper: 'The expense description cannot exceed 100 characters.',
        expenseQuantity: 'Quantity',
        expenseUnitPrice: 'Unit Price',
        expenseForeignCurrency: 'Foreign currency payment',
        cash: 'Cash',
        paymentMethod: 'Payment method',
        newPaymentLabel: 'Add payment method',
        paymentForeignCurrency: 'Foreign currency payment',
        expenseAddAction: 'Expense added',
        addedExpenseActionSuccess: 'The expense has been added successfully.',
        expenseFavSave: 'Save to favourites',
        expenseFavLoad: 'Load from favourites',
        expenseFavTitle: 'Expense favourites',
        expenseFavDelete: 'Delete this favourite',
        expenseFavEmpty: 'No saved favourites yet',
        expenseFavSaved: 'Saved to favourites.',
        loadingArrival: 'Arrival for loading',
        loadingArrivalAction: 'Arrival for loading',
        loadingArrivalSuccess: 'The arrival for loading was recorded successfully.',
        loadingCompleted: 'Loading completed',
        loadingCompletedAction: 'Loading completed',
        loadingCompletedSuccess: 'Loading completed successfully entered.',
        loadingSenderSwitchLabel: 'enter the sender in the place of loading',
        loadingPlace: 'Loading place',
        loadingSender: 'Sender',
        loadingReceiver: 'Receiver',
        loadedVehicle: 'Loaded vehicle',
        vehicleDetailsNotFound: 'vehicle details not found',
        loadReference: 'Loading reference',
        loadDescription: 'Product description',
        loadWeight: 'Weight of the goods',
        loadQuantity: 'Quantity of the goods',
        unloadingArrival: 'Ariving at unloading',
        unloadingArrivalSuccess: 'The arrival for loading was recorded successfully.',
        unloadingArrivalAction: `Arrival for unloading`,
        unloadingCompleted: 'Unloading completed',
        unloadingCompletedAction: `Unloading completed`,
        unloadingCompletedSuccess: 'Unloading completed successfully entered.',
        unloadingLoadSelectLabel: 'enter the receiver in the place of unloading',
        chooseLoad: 'Choose your load',
        noLoadReceiver: 'no receiver entered',
        attachTrailer: 'Attach Trailer',
        attachTrailerAction: 'Trailer attached',
        attachTrailerSuccess: 'The trailer has been connected successfully.',
        trailerNoValid: 'Please enter trailer number.',
        detachTrailer: 'Drop Trailer',
        detachTrailerAction: 'Trailer Dropped',
        detachTrailerSuccess: 'The trailer has been dropped successfully.',
        tourStart: 'Start your tour',
        tourStop: 'Finish your tour',
        tourExist: 'You have already started a tour, so you cannot start another one.',
        noActiveRoute: `You don't have an active tour, so you cannot record this activity.`,
        startedTour: 'Your tour has started.',
        startedTourAction: 'The tour has started',
        finishedTour: 'Your tour has been finished.',
        finishedTourAction: 'Tour completed',
        truckNoValid: 'Please enter the truck number.',
        tourStopHelper1: `The proposed value was calculated from the on-board computer data. It's recommended to measure it manually to increase the accuracy of the fuel consumption results.`,
        finishTourUnloadedLoadsConfirm: (x) => `You are trying to finish the tour even though you still have ${x}. If you finish the tour, they will be described in the system as unloaded, with a note that they were marked so because of the end of the tour.`,
        finishTourUnloadNote: 'Marked as unloaded due to end of tour',
        tourStartKeepTrailerConfirm: (x) => `Do you still have trailer ${x} from the previous tour attached? If yes, it will be attached automatically.`,
        tourStartKeepLoadConfirm: (x) => `Are you still carrying the load ${x}? If yes, it will be added automatically as a new load.`,
        trailerAttachedBySystemNote: 'Trailer attached automatically by the system – continuation from the previous tour',
        loadAddedBySystemNote: 'Load added automatically by the system – continuation from the previous tour',
        addService: 'Service / Maintenance',
        addLubrication: '5th wheel lubrication',
        addServiceSuccess: 'Vehicle service activity successfully added.',
        addServiceAction: (x) => `Vehicle maintenance/service entry added${x ? ' ' + x : ''}`,
        chooseServicedVehicle: 'You must select the serviced vehicle.',
        noServiceEntry: 'You must enter a description of the repair/action.',
        startedDay: 'You have started your working day.',
        finishedDay: 'You have finished your working day.',
        borderCrossSuccess: 'Border crossing entered successfully.',
        trailerExist: 'You have already entered the connected trailer',
        noTrailer: `You don't have a trailer attached that you could unhook.`,
        dayExistRegardRoute: 'You cannot finish your route until you finish your current working day.',
        detachTrailerConfirm: (x) => `You are trying to unhook the trailer even though you still have ${x === '1' ? 'unloaded load.' : 'unloaded loads.'} If you detach the trailer now, they will be entered as unloaded in the current place with a note that the trailer was detached.`,
        tourStopHelperDistance: (x) => `You passed ${x}.`,
        tourStopHelperCombustion: (x) => `Avg. fuel usage: ${x}`,
        resumeDayButton: 'Resume previous working day',
        resumeDayConfirm: (x) => `Your previous working day started at ${x} — it looks like the break was not a full rest. Do you want to resume that day instead of starting a new one?`,
        resumedDay: 'Your working day has been resumed.',
        resumeDayAction: 'Resuming the day',
        addBreak: 'Add a break',
        driverChange: 'Driver change',
        addBreakSuccess: 'The entry has been added successfully.',
        addBreakAction: (x) => `Break taken: ${x}`,
        changeSlot1Action: 'Card change to slot 1',
        changeSlot2Action: 'Card change to slot 2',
        breakTakenLabel: 'Break taken',
        breakDriveTimeLabel: 'Drive time',
        breakDriveTimeHelper: 'This time will be added to the drive time of the whole day.',
        addDriveTimeSwitch: 'Add drive time',
        addDriveTimeLabel: 'Time to add',
        breakOnlyBreakSwitch: 'Enter break only',
        changeToSlot1: 'Change to slot 1',
        changeToSlot2: 'Change to slot 2',
        myCardInSlot1: 'Your card is in slot 1',
        userNotes: 'Notes',
        notesHistory: 'Notes history',
        notesHistoryTitle: 'Notes history',
        carriedDataError: 'The tour has been started, but the trailer/loads from the previous tour could not be restored.',
    },
    pl: {
        blockedDescription: 'Twoje konto jest nieaktywne. Jeżeli chcesz je aktywować i zyskać tym samym pełną funkcjonalność aplikacji - skontaktuj się z Administratorem.',
        dayStart: 'Rozpocznij dzień pracy',
        dayStop: 'Zakończ dzień pracy',
        dayExist: 'Masz już rozpoczęty dzień pracy, więc nie możesz zacząć kolejnego do póki go nie zakończysz.',
        dayNotExist: 'Nie masz rozpoczętego dnia pracy który mógłbyś zakończyć.',
        crossBorder: 'Przekroczenie granicy',
        crossBorderSwitchToAdd: 'Dodaj nowe przejście graniczne',
        crossBorderSwitchToChoose: 'Wybierz przejście graniczne',
        border: 'Granica',
        crossBorderYouAre: (x) => `Jesteś teraz w ${x}. Wybierz kraj do którego chcesz wjechać:`,
        addLog: 'Dodaj inną czynność',
        addLogSuccess: (x) => `Dodano inną czynność: ${x}.`,
        adblueRefuel: 'Tankowanie adblue',
        dieselRefuel: 'Tankowanie diesel',
        addExpense: 'Dodaj wydatek',
        startedDayAction: 'Rozpoczęcie dnia',
        startedDayActionCardInsert: '(włożenie karty)',
        finishedDayAction: 'Zakończenie dnia',
        finishedDayActionCardTakeOut: '(wyjęcie karty)',
        expenseItemDescription: 'Pozycja (opis wydatku)',
        expenseItemDescriptionHelper: 'Opis wydatku nie może przekraczać 100 znaków.',
        expenseQuantity: 'Ilość',
        expenseUnitPrice: 'Cena jednostkowa',
        expenseForeignCurrency: 'Płatność w obcej walucie',
        cash: 'Gotówka',
        paymentMethod: 'Metoda płatności',
        newPaymentLabel: 'Dodaj metodę płatności',
        paymentForeignCurrency: 'Płatność w obcej walucie',
        expenseAddAction: 'Dodano wydatek',
        addedExpenseActionSuccess: 'Pomyślnie wpisano wydatek.',
        expenseFavSave: 'Zapisz w ulubionych',
        expenseFavLoad: 'Wczytaj z ulubionych',
        expenseFavTitle: 'Ulubione wydatki',
        expenseFavDelete: 'Usuń tę pozycję z ulubionych',
        expenseFavEmpty: 'Brak zapisanych ulubionych',
        expenseFavSaved: 'Zapisano w ulubionych.',
        loadingArrival: 'Dojazd na załadunek',
        loadingArrivalAction: 'Dojazd na załadunek',
        loadingArrivalSuccess: 'Dojazd na załadunek został zapisany pomyślnie.',
        loadingCompleted: 'Zakończenie załadunku',
        loadingCompletedAction: 'Zakończenie załadunku',
        loadingCompletedSuccess: 'Pomyślnie wpisano zakończenie załadunku.',
        loadingSenderSwitchLabel: 'wpisz nadawcę w miejsce załadunku',
        loadingPlace: 'Miejsce załadunku',
        loadingSender: 'Nadawca',
        loadingReceiver: 'Odbiorca',
        loadedVehicle: 'Ładowany pojazd',
        vehicleDetailsNotFound: 'nie znaleziono danych pojazdu',
        loadReference: 'Numer załadunku',
        loadDescription: 'Opis towrau',
        loadWeight: 'Waga towaru',
        loadQuantity: 'Ilość towaru',
        unloadingArrival: 'Dojazd na rozładunek',
        unloadingArrivalSuccess: 'Dojazd na rozładunek został zapisany pomyślnie.',
        unloadingArrivalAction: `Dojazd na rozładunek`,
        unloadingCompleted: 'Zakończenie rozładunku',
        unloadingCompletedAction: `Zakończenie rozładunku`,
        unloadingCompletedSuccess: 'Pomyślnie wpisano zakończenie rozładunku.',
        unloadingLoadSelectLabel: 'wpisz odbiorcę w miejsce rozładunku',
        chooseLoad: 'Wybierz ładunek',
        noLoadReceiver: 'nie podano odbiorcy',
        attachTrailer: 'Podepnij naczepę',
        attachTrailerAction: 'Podpięto naczepę',
        attachTrailerSuccess: 'Naczepa została podpięta pomyślnie.',
        trailerNoValid: 'Podaj nr. rej. naczepy.',
        detachTrailer: 'Odepnij naczepę',
        detachTrailerAction: 'Odpięto naczepę',
        detachTrailerSuccess: 'Naczepa została odpięta pomyślnie.',
        tourStart: 'Rozpocznij trasę',
        tourStop: 'Zakończ trasę',
        tourExist: 'Masz już rozpoczętą trasę, więc nie możesz rozpocząć kolejnej.',
        noActiveRoute: 'Nie masz rozpoczętej trasy, więc nie możesz wykonać tej czynności.',
        startedTour: 'Twoja trasa została rozpoczęta.',
        startedTourAction: 'Rozpoczęto trasę',
        finishedTour: 'Twoja trasa została zakończona.',
        finishedTourAction: 'Zakończono trasę',
        truckNoValid: 'Podaj nr. rej. ciągnika.',
        tourStopHelper1: 'Proponowaną wartość wyliczono na podstawie danych komputera pokładowego. Zaleca się dokonać ręcznego pomiaru celem zwiększenia dokładności wyników spalania.',
        finishTourUnloadedLoadsConfirm: (x) => `Próbujesz zakończyć trasę pomimo, że masz jeszcze ${x}. Jeżeli zakończysz trasę, zostaną one w systemie opisane jako rozładowane z adnotacją w notatkach, że oznaczono je tak z powodu zakończenia trasy.`,
        finishTourUnloadNote: 'Oznaczony jako rozładowany z powodu zakończenia trasy',
        tourStartKeepTrailerConfirm: (x) => `Czy nadal masz podpiętą naczepę ${x} z poprzedniej trasy? Jeżeli tak, zostanie automatycznie podpięta.`,
        tourStartKeepLoadConfirm: (x) => `Czy nadal wieziesz ładunek ${x}? Jeżeli tak, zostanie automatycznie dodany jako nowy ładunek.`,
        trailerAttachedBySystemNote: 'Naczepa podpięta automatycznie – kontynuacja z poprzedniej trasy',
        loadAddedBySystemNote: 'Ładunek dodany automatycznie – kontynuacja z poprzedniej trasy',
        addService: 'Serwis / Obsługa',
        addLubrication: 'Smarowanie siodła',
        addServiceSuccess: 'Pomyślnie dodano czynność serwisową pojazdu.',
        addServiceAction: (x) => `Dodano wpis obsługi/serwisu pojazdu${x ? ' ' + x : ''}`,
        chooseServicedVehicle: 'Musisz wybrać serwisowany pojazd.',
        noServiceEntry: 'Musisz podać opis naprawy / czynności.',
        startedDay: 'Rozpocząłeś swój dzień pracy.',
        finishedDay: 'Zakończyłeś swój dzień pracy.',
        borderCrossSuccess: 'Pomyślnie wpisano przekroczenie granicy.',
        trailerExist: 'Masz już wpisaną podpiętą przyczepę.',
        noTrailer: 'Nie masz żadnej podpiętej naczepy do odpięcia.',
        dayExistRegardRoute: 'Nie możesz zakończyć trasy do póki nie zakończysz obecnego dnia pracy.',
        detachTrailerConfirm: (x) => `Próbujesz odczepić naczepę mimo, że masz ciągle ${x} ${x === '1' ? 'nierozładowany ładunek.' : 'nierozładowane ładunki.'} Jeżeli odczepisz teraz naczepę to zostaną one wpisane jako rozładowane w obecnym miejscu z adnotacją, że była odczepiona naczepa.`,
        tourStopHelperDistance: (x) => `Przejechałeś ${x}.`,
        tourStopHelperCombustion: (x) => `Spalanie: ${x}`,
        resumeDayButton: 'Wznów poprzedni dzień pracy',
        resumeDayConfirm: (x) => `Twój poprzedni dzień pracy rozpoczął się o ${x} — wygląda na to, że przerwa nie była pełnym odpoczynkiem. Czy chcesz wznowić tamten dzień zamiast rozpoczynać nowy?`,
        resumedDay: 'Twój dzień pracy został wznowiony.',
        resumeDayAction: 'Wznowienie dnia',
        addBreak: 'Dodaj przerwę',
        driverChange: 'Zmiana kierowcy',
        addBreakSuccess: 'Wpis został pomyślnie dodany.',
        addBreakAction: (x) => `Zrobiono przerwę: ${x}`,
        changeSlot1Action: 'Zmiana karty na 1 slot',
        changeSlot2Action: 'Zmiana karty na 2 slot',
        breakTakenLabel: 'Zrobiona przerwa',
        breakDriveTimeLabel: 'Czas jazdy',
        breakDriveTimeHelper: 'Ten czas zostanie dodany do czasu jazdy z całego dnia.',
        addDriveTimeSwitch: 'Dopisz czas jazdy',
        addDriveTimeLabel: 'Czas do dopisania',
        breakOnlyBreakSwitch: 'Wpisz tylko przerwę',
        changeToSlot1: 'Zmiana na 1 slot',
        changeToSlot2: 'Zmiana na 2 slot',
        myCardInSlot1: 'Twoja karta w 1 slocie',
        userNotes: 'Notatki',
        notesHistory: 'Historia notatek',
        notesHistoryTitle: 'Historia notatek',
        carriedDataError: 'Trasa została rozpoczęta, ale nie udało się odtworzyć naczepy/ładunków z poprzedniej trasy.',
    },
}