import { HomeInterface } from "@/types/text/HomeInterface";

export const home: HomeInterface = {
    en: {
        blockedDescription: `Your account is inactive. If you wish to activate it and gain full access to the application's features, please contact the Administrator.`,
        dayStart: 'Start working day',
        dayStop: 'Finish working day',
        dayExist: `You've already started your working day, so you can't start the next one until you finish it.`,
        dayNotExist: 'You don\'t have a working day that you could finish.',
        crossBorder: 'Border cross',
        crossBorderSwitchToAdd: 'Add new border crossing',
        crossBorderSwitchToChoose: 'Choose border crossing',
        border: 'Border',
        crossBorderYouAre: (x) => `You are now in ${x}. Select the country you want to enter:`,
        addLog: 'Add other activity',
        addLogSuccess: (x) => `Activity added: ${x}.`,
        adblueRefuel: 'Adblue(Def) refueling',
        dieselRefuel: 'Diesel refueling',
        addExpense: 'Add expence',
        startedDayAction: 'Starting the day',
        startedDayActionCardInsert: '(card insert)',
        finishedDayAction: 'End of the day',
        finishedDayActionCardTakeOut: '(card take out)',
        expenseItemDescription: 'Item (expense description)',
        expenseItemDescriptionHelper: 'The expense description cannot exceed 100 characters.',
        expenseQuantity: 'Quantity',
        expenseUnitPrice: 'Unit Price',
        expenseForeignCurrency: 'Foreign currency payment',
        cash: 'Cash',
        paymentMethod: 'Payment method',
        newPaymentLabel: 'Add payment method',
        paymentForeignCurrency: 'Foreign currency payment',
        expenseAddAction: 'Expense added',
        addedExpenseActionSuccess: 'The expense has been added successfully.',
        loadingArrival: 'Arrival for loading',
        loadingArrivalAction: 'Arrival for loading',
        loadingArrivalSuccess: 'The arrival for loading was recorded successfully.',
        loadingCompleted: 'Loading completed',
        loadingCompletedAction: 'Loading completed',
        loadingCompletedSuccess: 'Loading completed successfully entered.',
        loadingSenderSwitchLabel: 'enter the sender in the place of loading',
        loadingPlace: 'Loading place',
        loadingSender: 'Sender',
        loadingReceiver: 'Receiver',
        loadedVehicle: 'Loaded vehicle',
        vehicleDetailsNotFound: 'vehicle details not found',
        loadReference: 'Loading reference',
        loadDescription: 'Product description',
        loadWeight: 'Weight of the goods',
        loadQuantity: 'Quantity of the goods',
        unloadingArrival: 'Ariving at unloading',
        unloadingArrivalSuccess: 'The arrival for loading was recorded successfully.',
        unloadingArrivalAction: `Arrival for unloading`,
        unloadingCompleted: 'Unloading completed',
        unloadingCompletedAction: `Unloading completed`,
        unloadingCompletedSuccess: 'Unloading completed successfully entered.',
        unloadingLoadSelectLabel: 'enter the receiver in the place of unloading',
        chooseLoad: 'Choose your load',
        noLoadReceiver: 'no receiver entered',
        attachTrailer: 'Attach Trailer',
        attachTrailerAction: 'Trailer attached',
        attachTrailerSuccess: 'The trailer has been connected successfully',
        trailerNoValid: 'Please enter trailer number.',
    },
    pl: {
        blockedDescription: 'Twoje konto jest nieaktywne. Jeżeli chcesz je aktywować i zyskać tym samym pełną funkcjonalność aplikacji - skontaktuj się z Administratorem.',
        dayStart: 'Rozpocznij dzień pracy',
        dayStop: 'Zakończ dzień pracy',
        dayExist: 'Masz już rozpoczęty dzień pracy, więc nie możesz zacząć kolejnego do póki go nie zakończysz.',
        dayNotExist: 'Nie masz rozpoczętego dnia pracy który mógłbyś zakończyć.',
        crossBorder: 'Przekroczenie granicy',
        crossBorderSwitchToAdd: 'Dodaj nowe przejście graniczne',
        crossBorderSwitchToChoose: 'Wybierz przejście graniczne',
        border: 'Granica',
        crossBorderYouAre: (x) => `Jesteś teraz w ${x}. Wybierz kraj do którego chcesz wjechać:`,
        addLog: 'Dodaj inną czynność',
        addLogSuccess: (x) => `Dodano inną czynność: ${x}.`,
        adblueRefuel: 'Tankowanie adblue',
        dieselRefuel: 'Tankowanie diesel',
        addExpense: 'Dodaj wydatek',
        startedDayAction: 'Rozpoczęcie dnia',
        startedDayActionCardInsert: '(włożenie karty)',
        finishedDayAction: 'Zakończenie dnia',
        finishedDayActionCardTakeOut: '(wyjęcie karty)',
        expenseItemDescription: 'Pozycja (opis wydatku)',
        expenseItemDescriptionHelper: 'Opis wydatku nie może przekraczać 100 znaków.',
        expenseQuantity: 'Ilość',
        expenseUnitPrice: 'Cena jednostkowa',
        expenseForeignCurrency: 'Płatność w obcej walucie',
        cash: 'Gotówka',
        paymentMethod: 'Metoda płatności',
        newPaymentLabel: 'Dodaj metodę płatności',
        paymentForeignCurrency: 'Płatność w obcej walucie',
        expenseAddAction: 'Dodano wydatek',
        addedExpenseActionSuccess: 'Pomyślnie wpisano wydatek.',
        loadingArrival: 'Dojazd na załadunek',
        loadingArrivalAction: 'Dojazd na załadunek',
        loadingArrivalSuccess: 'Dojazd na załadunek został zapisany pomyślnie.',
        loadingCompleted: 'Zakończenie załadunku',
        loadingCompletedAction: 'Zakończenie załadunku',
        loadingCompletedSuccess: 'Pomyślnie wpisano zakończenie załadunku.',
        loadingSenderSwitchLabel: 'wpisz nadawcę w miejsce załadunku',
        loadingPlace: 'Miejsce załadunku',
        loadingSender: 'Nadawca',
        loadingReceiver: 'Odbiorca',
        loadedVehicle: 'Ładowany pojazd',
        vehicleDetailsNotFound: 'nie znaleziono danych pojazdu',
        loadReference: 'Numer załadunku',
        loadDescription: 'Opis towrau',
        loadWeight: 'Waga towaru',
        loadQuantity: 'Ilość towaru',
        unloadingArrival: 'Dojazd na rozładunek',
        unloadingArrivalSuccess: 'Dojazd na rozładunek został zapisany pomyślnie.',
        unloadingArrivalAction: `Dojazd na rozładunek`,
        unloadingCompleted: 'Zakończenie rozładunku',
        unloadingCompletedAction: `Zakończenie rozładunku`,
        unloadingCompletedSuccess: 'Pomyślnie wpisano zakończenie rozładunku.',
        unloadingLoadSelectLabel: 'wpisz odbiorcę w miejsce rozładunku',
        chooseLoad: 'Wybierz ładunek',
        noLoadReceiver: 'nie podano odbiorcy',
        attachTrailer: 'Podepnij naczepę',
        attachTrailerAction: 'Podpięto naczepę',
        attachTrailerSuccess: 'Naczepa została podpięta pomyślnie.',
        trailerNoValid: 'Podaj nr. rej. naczepy.',
    },
}