import { HomeInterface } from "@/types/text/HomeInterface";

export const home: HomeInterface = {
    en: {
        blockedDescription: `Your account is inactive. If you wish to activate it and gain full access to the application's features, please contact the Administrator.`,
        dayStart: 'Start working day',
        dayStop: 'Finish working day',
        dayExist: `You've already started your working day, so you can't start the next one until you finish it.`,
        dayNotExist: 'You don\'t have a working day that you could finish.',
        crossBorder: 'Border cross',
        crossBorderSwitchToAdd: 'Add new border crossing',
        crossBorderSwitchToChoose: 'Choose border crossing',
        border: 'Border',
        crossBorderYouAre: (x) => `You are now in ${x}. Select the country you want to enter:`,
        addLog: 'Add other activity',
        addLogSuccess: (x) => `Activity added: ${x}.`,
        adblueRefuel: 'Adblue(Def) refueling',
        dieselRefuel: 'Diesel refueling',
        expenceAdd: 'Add expence',
        startedDayAction: 'Starting the day',
        startedDayActionCardInsert: '(card insert)',
        finishedDayAction: 'End of the day',
        finishedDayActionCardTakeOut: '(card take out)',
    },
    pl: {
        blockedDescription: 'Twoje konto jest nieaktywne. Jeżeli chcesz je aktywować i zyskać tym samym pełną funkcjonalność aplikacji - skontaktuj się z Administratorem.',
        dayStart: 'Rozpocznij dzień pracy',
        dayStop: 'Zakończ dzień pracy',
        dayExist: 'Masz już rozpoczęty dzień pracy, więc nie możesz zacząć kolejnego do póki go nie zakończysz.',
        dayNotExist: 'Nie masz rozpoczętego dnia pracy który mógłbyś zakończyć.',
        crossBorder: 'Przekroczenie granicy',
        crossBorderSwitchToAdd: 'Dodaj nowe przejście graniczne',
        crossBorderSwitchToChoose: 'Wybierz przejście graniczne',
        border: 'Granica',
        crossBorderYouAre: (x) => `Jesteś teraz w ${x}. Wybierz kraj do którego chcesz wjechać:`,
        addLog: 'Dodaj inną czynność',
        addLogSuccess: (x) => `Dodano inną czynność: ${x}.`,
        adblueRefuel: 'Tankowanie adblue',
        dieselRefuel: 'Tankowanie diesel',
        expenceAdd: 'Dodaj wydatek',
        startedDayAction: 'Rozpoczęcie dnia',
        startedDayActionCardInsert: '(włożenie karty)',
        finishedDayAction: 'Zakończenie dnia',
        finishedDayActionCardTakeOut: '(wyjęcie karty)',
    },
}