import { InfoInterface } from "@/types/text/InfoInterface";

export const info: InfoInterface = {
    en: {
        title: 'Info',
        noActiveTour: 'You have no active tour.',
        routeNo: 'Route no.',
        distance: 'Traveled distance',
        lasts: 'Lasts',
        and: 'and',
        day: 'day',
        days: 'days',
        in: 'in',
        youStartedDayAt: 'You started the day at',
        traveledToday: 'Traveled today',
        workingTimeUntil: 'Working time until',
        dayTitle: 'Working day',
        tourSetTitle: 'Vehicle set',
        truck: 'Truck',
        trailer: 'Trailer',
        fuel: 'Fuel',
        actualMass: 'Actual mass',
        noDataInfo: 'To know the weight, enter the vehicle details.',
        empty: 'empty',
        destination: 'Destination',
        delete: 'Delete',
        deleteSuccess: 'Marked place was removed successfully.',
        noActiveDay: `You haven't started your working day.`,
        breakLasts: 'Break lasts',
        break9HourEnd: 'The 9-hour break will end at',
        break11HourEnd: 'The 11-hour break will end at',
        breakOver: 'The required daily break has been completed',
        breakIn: 'in',
        carriedLoads: 'Carried loads',
        model: 'Brand/model',
        isLoadable: 'Loadable',
        tankCapacity: 'Tank capacity',
        yearOfProduction: 'Year of production',
        weightDisp: 'Weight',
        techRev: 'Next technical review',
        insurance: 'Insurance validity',
        tacho: 'Next tachograph inspection',
        nextService: 'Next service at',
        notes: 'Additional information',
        yes: 'Yes',
        no: 'No',
        expired: 'expired',
    },
    pl: {
        title: 'Info',
        noActiveTour: 'Nie masz aktywnej trasy.',
        routeNo: 'Trasa nr',
        distance: 'Przejechany dystans',
        lasts: 'Trwa',
        and: 'i',
        day: 'dzień',
        days: 'dni',
        in: 'w',
        youStartedDayAt: 'Rozpocząłeś dzień o',
        traveledToday: 'Dziś przejechałeś',
        workingTimeUntil: 'Czas pracy do',
        dayTitle: 'Dzień pracy',
        tourSetTitle: 'Zestaw',
        truck: 'Ciągnik',
        trailer: 'Naczepa',
        fuel: 'Paliwo',
        actualMass: 'Masa rzeczywista',
        noDataInfo: 'Aby znać masę zestawu, wpisz dane pojazdu.',
        empty: 'pusty',
        destination: 'Oznaczono',
        delete: 'Usuń',
        deleteSuccess: 'Pomyślnie usunięto oznaczone miejsce.',
        noActiveDay: 'Nie masz rozpoczętego dnia pracy.',
        breakLasts: 'Przerwa trwa',
        break9HourEnd: '9h przerwy upłynie o',
        break11HourEnd: '11h przerwy upłynie o',
        breakOver: 'Wymagany odpoczynek dobowy został już odebrany',
        breakIn: 'za',
        carriedLoads: 'Przewożone ładunki',
        model: 'Marka/model',
        isLoadable: 'Pojazd ładowalny',
        tankCapacity: 'Pojemność zbiorników paliwa',
        yearOfProduction: 'Rok produkcji',
        weightDisp: 'Waga pojazdu',
        techRev: 'Przegląd techniczny',
        insurance: 'Ubezpieczenie OC',
        tacho: 'Legalizacja tachografu',
        nextService: 'Następna obsługa serwisowa',
        notes: 'Dodatkowe informacje',
        yes: 'Tak',
        no: 'Nie',
        expired: 'po terminie',
    },
};
