import { PlacesInterface } from "@/types/text/PlacesInterface";

export const places: PlacesInterface = {
    en: {
        listTitle: 'Address List',
        apiError: 'The place list could not be loaded due to a network problem or login session timeout.',
        empty: 'No places to show.',
        filterType: 'Group',
        filterCountry: 'Country',
        search: 'Search',
        thType: 'Group',
        thCountry: 'Country',
        thCity: 'City',
        thNameStreet: 'Name - street',
        gps: 'GPS',
        description: 'Description/Notes',
        directions: 'Directions',
        openInMaps: 'Open in Google Maps (address)',
        openGps: 'Open in Google Maps (GPS)',
        markAsDestination: 'Mark as destination',
        markedSuccess: 'Marked as destination point:',
        markedError: 'Something went wrong with the place marking. Check your connection or try again later.',
        edit: 'Edit',
        showActivities: 'Activities of this place',
        addPlace: 'Add new place',
        editPlace: 'Edit place',
        submitAdd: 'Add',
        submitEdit: 'Save',
        type: 'Group',
        name: 'Company name',
        street: 'Street',
        code: 'Post code',
        city: 'City',
        country: 'Country',
        lat: 'GPS latitude',
        lon: 'GPS longitude',
        isFavorite: 'add to favourites',
        isDestination: 'mark as destination',
        addSuccess: 'Place added successfully.',
        editSuccess: 'The chosen place has been successfully edited.',
        nameRequired: 'Please enter name of the place.',
        cityRequired: 'Please enter city of the place.',
        countryRequired: 'Please select country.',
        placeLogsHeader: (x) => `Activities of the place: ${x}`,
        logsEmpty: 'No activities for this place.',
        logsApiError: 'Your activity list could not be downloaded due to a connection problem. Please try again later.',
        logTour: 'Route',
        logDate: 'Date',
        logAction: 'Activity',
        logCountry: 'Country',
        logPlace: 'Place',
        logOdometer: 'Odometer',
        logNotes: 'Notes',
        logEdit: 'Edit',
        logEditHeader: 'Edit your activity',
        logEditSuccess: 'The selected activity has been successfully edited.',
    },
    pl: {
        listTitle: 'Lista adresowa',
        apiError: 'Lista miejsc nie może zostać wczytana przez problem z siecią lub sesja logowania wygasła.',
        empty: 'Brak adresów do wyświetlenia.',
        filterType: 'Grupa',
        filterCountry: 'Państwo',
        search: 'Szukaj',
        thType: 'Grupa',
        thCountry: 'Państwo',
        thCity: 'Miejscowość',
        thNameStreet: 'Nazwa - ulica',
        gps: 'GPS',
        description: 'Opis/Notatki',
        directions: 'Adres',
        openInMaps: 'Otwórz w Google Maps (adres)',
        openGps: 'Otwórz w Google Maps (GPS)',
        markAsDestination: 'Oznacz jako cel',
        markedSuccess: 'Oznaczono jako miejsce docelowe:',
        markedError: 'Coś poszło nie tak z oznaczeniem miejsca. Sprawdź połączenie lub spróbuj później.',
        edit: 'Edytuj',
        showActivities: 'Czynności tego miejsca',
        addPlace: 'Dodaj nowy adres',
        editPlace: 'Edytuj adres',
        submitAdd: 'Dodaj',
        submitEdit: 'Zapisz',
        type: 'Grupa',
        name: 'Nazwa firmy',
        street: 'Ulica',
        code: 'Kod pocztowy',
        city: 'Miejscowość',
        country: 'Państwo',
        lat: 'GPS szerokość geo.',
        lon: 'GPS długość geo.',
        isFavorite: 'dodaj do ulubionych',
        isDestination: 'oznacz jako cel',
        addSuccess: 'Miejsce dodano pomyślnie.',
        editSuccess: 'Wybrane miejsce zostało edytowane pomyślnie.',
        nameRequired: 'Nie podano nazwy dodawanego miejsca.',
        cityRequired: 'Nie podano miejscowości.',
        countryRequired: 'Nie podano kraju.',
        placeLogsHeader: (x) => `Czynności miejsca: ${x}`,
        logsEmpty: 'Brak czynności dla tego miejsca.',
        logsApiError: 'Twoja lista czynności nie mogła zostać pobrana z powodu problemu z połączeniem. Spróbuj ponownie później.',
        logTour: 'Trasa',
        logDate: 'Data',
        logAction: 'Czynność',
        logCountry: 'Kraj',
        logPlace: 'Miejsce',
        logOdometer: 'Przebieg',
        logNotes: 'Notatki',
        logEdit: 'Edytuj',
        logEditHeader: 'Edytuj czynność',
        logEditSuccess: 'Wybrana czynność została pomyślnie edytowana.',
    },
};
