import { ToursInterface } from "@/types/text/ToursInterface";

export const tours: ToursInterface = {
    en: {
        listTitle: 'Routes',
        noTours: 'No unaccounted routes.',
        apiError: 'Failed to download the data. Please try again later.',
        tour: 'Route',
        tours: 'Routes',
        na: '- - -',
        tabUnaccounted: 'Unaccounted',
        tabSettled: 'Settled',
        tabStats: 'Statistics',
        settlementsTitle: 'Monthly settlements',
        noSettlements: 'No settlements for this year.',
        month: 'Month',
        viewRouteList: 'Show routes',
        settledRoutesTitle: 'Settled routes',
        deleteSettlement: 'Delete settlement',
        deleteSettlementConfirm: 'Delete this settlement? Its routes will be marked as unsettled.',
        deleteSettlementSuccess: 'The monthly settlement has been deleted.',
        statsNoData: 'No completed tours yet.',
        statsTotal: 'All-time totals',
        statsByMonth: 'By month',
        year: 'Year',
        truck: 'Truck',
        distance: 'Distance',
        fuelUsage: 'Fuel usage',
        salary: 'Salary',
        predicted: 'predicted',
        real: 'real',
        outgoings: 'Outgoings',
        sectionTime: 'Time',
        sectionFuel: 'Fuel',
        sectionLoads: 'Loads',
        sectionSalary: 'Earnings',
        driveTime: 'Drive time',
        workTime: 'Work time',
        onDuty: 'On-duty days',
        offDuty: 'Off-duty days',
        fuel: 'Fuel',
        before: 'before',
        after: 'after',
        burned: 'Burned',
        boardComputer: 'board comp.',
        refueled: 'Refueled',
        averageLoadWeight: 'Avg. load weight',
        numberOfLoads: 'Number of loads',
        rate: 'Rate',
        perKm: 'per km',
        perHour: 'per hour',
        perDay: 'per day',
        startNotes: 'Start notes',
        stopNotes: 'End notes',
        showLogs: 'Activities',
        showDays: 'Working days',
        showFinances: 'Finances',
        showLoads: 'Loads',
        generate: 'Generate route settlement',
        generateSoon: 'The settlement generator is coming soon to the mobile app.',
        noRecords: 'No entries.',
        logsTitle: 'Activities',
        activity: 'Activity',
        country: 'Country',
        place: 'Place',
        odometer: 'Odometer',
        notes: 'Notes',
        daysTitle: 'Working days',
        start: 'Start',
        stop: 'End',
        breakTime: 'Break',
        secondDriver: '2nd driver',
        financesTitle: 'Finances',
        description: 'Item',
        quantity: 'Quantity',
        unitPrice: 'Unit price',
        amount: 'Amount',
        foreignAmount: 'Foreign amount',
        payment: 'Payment',
        loadsTitle: 'Loads',
        loadNr: 'Load no.',
        loading: 'Loading',
        unloading: 'Unloading',
        notUnloaded: 'not unloaded',
        sender: 'Sender',
        receiver: 'Receiver',
        reference: 'Reference',
        vehicle: 'Vehicle',
        weight: 'Weight',
    },
    pl: {
        listTitle: 'Trasy',
        noTours: 'Brak tras nierozliczonych.',
        apiError: 'Nie udało się pobrać danych. Spróbuj ponownie później.',
        tour: 'Trasa',
        tours: 'Trasy',
        na: '- - -',
        tabUnaccounted: 'Nierozliczone',
        tabSettled: 'Rozliczone',
        tabStats: 'Statystyki',
        settlementsTitle: 'Rozliczenia miesięczne',
        noSettlements: 'Brak rozliczeń w tym roku.',
        month: 'Miesiąc',
        viewRouteList: 'Pokaż trasy',
        settledRoutesTitle: 'Trasy rozliczone',
        deleteSettlement: 'Usuń rozliczenie',
        deleteSettlementConfirm: 'Usunąć to rozliczenie? Jego trasy zostaną oznaczone jako nierozliczone.',
        deleteSettlementSuccess: 'Rozliczenie miesięczne zostało usunięte.',
        statsNoData: 'Brak zakończonych tras.',
        statsTotal: 'Podsumowanie ogółem',
        statsByMonth: 'Wg miesiąca',
        year: 'Rok',
        truck: 'Ciągnik',
        distance: 'Dystans',
        fuelUsage: 'Spalanie',
        salary: 'Wynagrodzenie',
        predicted: 'przewidywane',
        real: 'realne',
        outgoings: 'Wydatki',
        sectionTime: 'Czas',
        sectionFuel: 'Paliwo',
        sectionLoads: 'Ładunki',
        sectionSalary: 'Wynagrodzenie',
        driveTime: 'Czas jazdy',
        workTime: 'Czas pracy',
        onDuty: 'Dni pracy',
        offDuty: 'Dni przerwy',
        fuel: 'Paliwo',
        before: 'przed',
        after: 'po',
        burned: 'Spalono',
        boardComputer: 'komp. pok.',
        refueled: 'Zatankowano',
        averageLoadWeight: 'Śr. waga ładunku',
        numberOfLoads: 'Liczba ładunków',
        rate: 'Stawka',
        perKm: 'na km',
        perHour: 'na godzinę',
        perDay: 'na dzień',
        startNotes: 'Notatki (start)',
        stopNotes: 'Notatki (koniec)',
        showLogs: 'Czynności',
        showDays: 'Dni pracy',
        showFinances: 'Finanse',
        showLoads: 'Ładunki',
        generate: 'Generuj rozliczenie trasy',
        generateSoon: 'Generator rozliczeń pojawi się wkrótce w aplikacji mobilnej.',
        noRecords: 'Brak wpisów.',
        logsTitle: 'Czynności',
        activity: 'Czynność',
        country: 'Kraj',
        place: 'Miejsce',
        odometer: 'Licznik',
        notes: 'Notatki',
        daysTitle: 'Dni pracy',
        start: 'Rozpoczęcie',
        stop: 'Zakończenie',
        breakTime: 'Przerwa',
        secondDriver: '2. kierowca',
        financesTitle: 'Finanse',
        description: 'Pozycja',
        quantity: 'Ilość',
        unitPrice: 'Cena jedn.',
        amount: 'Kwota',
        foreignAmount: 'Kwota walutowa',
        payment: 'Płatność',
        loadsTitle: 'Ładunki',
        loadNr: 'Ładunek nr',
        loading: 'Załadunek',
        unloading: 'Rozładunek',
        notUnloaded: 'nierozładowany',
        sender: 'Nadawca',
        receiver: 'Odbiorca',
        reference: 'Numer referencyjny',
        vehicle: 'Pojazd',
        weight: 'Waga',
    },
};
