import { ToursInterface } from "@/types/text/ToursInterface";

export const tours: ToursInterface = {
    en: {
        listTitle: 'Routes',
        noTours: 'No unaccounted routes.',
        apiError: 'Failed to download the data. Please try again later.',
        tour: 'Route',
        tours: 'Routes',
        na: '- - -',
        tabUnaccounted: 'Unaccounted',
        tabSettled: 'Settled',
        tabStats: 'Statistics',
        settlementsTitle: 'Monthly settlements',
        noSettlements: 'No settlements for this year.',
        month: 'Month',
        viewRouteList: 'Show routes',
        settledRoutesTitle: 'Settled routes',
        deleteSettlement: 'Delete settlement',
        deleteSettlementConfirm: 'Delete this settlement? Its routes will be marked as unsettled.',
        deleteSettlementSuccess: 'The monthly settlement has been deleted.',
        statsNoData: 'No completed tours yet.',
        statsTotal: 'All-time totals',
        statsByMonth: 'By month',
        year: 'Year',
        truck: 'Truck',
        distance: 'Distance',
        fuelUsage: 'Fuel usage',
        salary: 'Salary',
        predicted: 'predicted',
        real: 'real',
        outgoings: 'Outgoings',
        sectionTime: 'Time',
        sectionFuel: 'Fuel',
        sectionLoads: 'Loads',
        sectionSalary: 'Earnings',
        driveTime: 'Drive time',
        workTime: 'Work time',
        onDuty: 'On-duty days',
        offDuty: 'Off-duty days',
        fuel: 'Fuel',
        before: 'before',
        after: 'after',
        burned: 'Burned',
        boardComputer: 'board comp.',
        refueled: 'Refueled',
        averageLoadWeight: 'Avg. load weight',
        numberOfLoads: 'Number of loads',
        rate: 'Rate',
        perKm: 'per km',
        perHour: 'per hour',
        perDay: 'per day',
        startNotes: 'Start notes',
        stopNotes: 'End notes',
        showLogs: 'Activities',
        showDays: 'Working days',
        showFinances: 'Finances',
        showLoads: 'Loads',
        generate: 'Generate route settlement',
        generateError: 'There was a problem generating the settlement. Try again.',
        generateTitle: (x) => `Settlement of route no ${x}`,
        generatorNotFound: "You don't have a template assigned. To be able to generate route settlements, you must contact the Administrator.",
        generatorTourEdit: 'Edit your route',
        generatorHint: 'Everything below goes to the PDF – check and correct the data, then generate the file.',
        generatorEmptyLeg: 'Empty row (to fill in manually)',
        generatorShareError: 'The PDF was created, but it could not be shared on this device.',
        generateAndOpen: 'Generate and open PDF',
        generatorOpenAgain: 'Open PDF again',
        generatorShare: 'Share PDF',
        generatorNoPdfApp: 'No app to open PDF files was found. Install a PDF app (e.g. Google Drive, Adobe Acrobat) or use "Share PDF".',
        generatorEditHint: 'After changing any field, generate the PDF again.',
        genSectionDrivers: 'Drivers',
        genSectionTour: 'Route',
        genSectionRefs: 'Load reference numbers',
        genSectionFuel: 'Fuel',
        genSectionExpenses: 'Expenses',
        genSectionLegs: 'Route legs',
        genSectionOther: 'Other',
        genDriver1: 'Driver 1',
        genDriver2: 'Driver 2',
        genRouteNr: 'Route no.',
        genDestination: 'Destinations',
        genTruck: 'Truck',
        genTrailer: 'Trailer(s)',
        genDepartureDate: 'Departure date',
        genDepartureTime: 'Departure time',
        genReturnDate: 'Return date',
        genReturnTime: 'Return time',
        genDepartureOdometer: 'Odometer at departure',
        genReturnOdometer: 'Odometer at return',
        genDistance: 'Distance',
        genRef: (x) => `Reference no. ${x}`,
        genFuelBefore: 'Fuel before the route',
        genFuelAfter: 'Fuel after the route',
        genFuelConsumption: 'Fuel usage (l/100 km)',
        genRefueled: 'Refueled in total',
        genFuelDate: (x) => `Refueling ${x} – date`,
        genFuelCity: (x) => `Refueling ${x} – place`,
        genFuelOdometer: (x) => `Refueling ${x} – odometer`,
        genFuelValue: (x) => `Refueling ${x} – quantity`,
        genExpense: (x) => `Expense ${x}`,
        genStops: 'Stops',
        genOther: 'Other remarks',
        genLeg: (x) => `Leg ${x}`,
        genAddLeg: 'Add leg',
        legStartCity: 'From',
        legStartData: 'Departure (date and time)',
        legStartOdometer: 'Odometer – start',
        legBorderDate: 'Border – date',
        legBorderPlace: 'Border – place',
        legStopCity: 'To',
        legStopData: 'Arrival (date and time)',
        legStopOdometer: 'Odometer – end',
        legDistance: 'Distance',
        legCustomer: 'Load',
        generatorSkippedLegs: (x) => `The template has no room for all legs – ${x} did not fit in the PDF. Merge or remove some legs.`,
        noRecords: 'No entries.',
        browseRecords: 'Browse entries',
        editRecord: 'Edit',
        showMoreFields: 'Show remaining fields',
        showLessFields: 'Hide extra fields',
        editSuccess: 'The entry has been saved.',
        logEditHeader: 'Edit activity',
        dayEditHeader: 'Edit working day',
        financeEditHeader: 'Edit expense',
        loadEditHeader: 'Edit load',
        sectionStart: 'Start',
        sectionStop: 'End',
        sectionLoading: 'Loading',
        sectionUnloading: 'Unloading',
        logsTitle: 'Activities',
        activity: 'Activity',
        country: 'Country',
        place: 'Place',
        odometer: 'Odometer',
        notes: 'Notes',
        daysTitle: 'Working days',
        start: 'Start',
        stop: 'End',
        breakTime: 'Break',
        secondDriver: '2nd driver',
        financesTitle: 'Finances',
        description: 'Item',
        quantity: 'Quantity',
        unitPrice: 'Unit price',
        amount: 'Amount',
        foreignAmount: 'Foreign amount',
        payment: 'Payment',
        loadsTitle: 'Loads',
        loadNr: 'Load no.',
        loading: 'Loading',
        unloading: 'Unloading',
        notUnloaded: 'not unloaded',
        sender: 'Sender',
        receiver: 'Receiver',
        reference: 'Reference',
        vehicle: 'Vehicle',
        weight: 'Weight',
    },
    pl: {
        listTitle: 'Trasy',
        noTours: 'Brak tras nierozliczonych.',
        apiError: 'Nie udało się pobrać danych. Spróbuj ponownie później.',
        tour: 'Trasa',
        tours: 'Trasy',
        na: '- - -',
        tabUnaccounted: 'Nierozliczone',
        tabSettled: 'Rozliczone',
        tabStats: 'Statystyki',
        settlementsTitle: 'Rozliczenia miesięczne',
        noSettlements: 'Brak rozliczeń w tym roku.',
        month: 'Miesiąc',
        viewRouteList: 'Pokaż trasy',
        settledRoutesTitle: 'Trasy rozliczone',
        deleteSettlement: 'Usuń rozliczenie',
        deleteSettlementConfirm: 'Usunąć to rozliczenie? Jego trasy zostaną oznaczone jako nierozliczone.',
        deleteSettlementSuccess: 'Rozliczenie miesięczne zostało usunięte.',
        statsNoData: 'Brak zakończonych tras.',
        statsTotal: 'Podsumowanie ogółem',
        statsByMonth: 'Wg miesiąca',
        year: 'Rok',
        truck: 'Ciągnik',
        distance: 'Dystans',
        fuelUsage: 'Spalanie',
        salary: 'Wynagrodzenie',
        predicted: 'przewidywane',
        real: 'realne',
        outgoings: 'Wydatki',
        sectionTime: 'Czas',
        sectionFuel: 'Paliwo',
        sectionLoads: 'Ładunki',
        sectionSalary: 'Wynagrodzenie',
        driveTime: 'Czas jazdy',
        workTime: 'Czas pracy',
        onDuty: 'Dni pracy',
        offDuty: 'Dni przerwy',
        fuel: 'Paliwo',
        before: 'przed',
        after: 'po',
        burned: 'Spalono',
        boardComputer: 'komp. pok.',
        refueled: 'Zatankowano',
        averageLoadWeight: 'Śr. waga ładunku',
        numberOfLoads: 'Liczba ładunków',
        rate: 'Stawka',
        perKm: 'na km',
        perHour: 'na godzinę',
        perDay: 'na dzień',
        startNotes: 'Notatki (start)',
        stopNotes: 'Notatki (koniec)',
        showLogs: 'Czynności',
        showDays: 'Dni pracy',
        showFinances: 'Finanse',
        showLoads: 'Ładunki',
        generate: 'Generuj rozliczenie trasy',
        generateError: 'Wystąpił problem z generowaniem rozliczenia. Spróbuj ponownie.',
        generateTitle: (x) => `Rozliczenie trasy nr ${x}`,
        generatorNotFound: 'Nie masz przydzielonego szablonu. Aby móc generować rozliczenia tras musisz skontaktować się z Administratorem.',
        generatorTourEdit: 'Edytuj przebieg trasy',
        generatorHint: 'Wszystko poniżej trafi do PDF – sprawdź i popraw dane, a potem wygeneruj plik.',
        generatorEmptyLeg: 'Pusty wiersz (do uzupełnienia ręcznie)',
        generatorShareError: 'PDF został utworzony, ale nie udało się go udostępnić na tym urządzeniu.',
        generateAndOpen: 'Generuj i otwórz PDF',
        generatorOpenAgain: 'Otwórz PDF ponownie',
        generatorShare: 'Udostępnij PDF',
        generatorNoPdfApp: 'Nie znaleziono aplikacji do otwierania PDF. Zainstaluj aplikację PDF (np. Dysk Google, Adobe Acrobat) albo użyj „Udostępnij PDF".',
        generatorEditHint: 'Po zmianie któregokolwiek pola wygeneruj PDF ponownie.',
        genSectionDrivers: 'Kierowcy',
        genSectionTour: 'Trasa',
        genSectionRefs: 'Numery referencyjne ładunków',
        genSectionFuel: 'Paliwo',
        genSectionExpenses: 'Wydatki',
        genSectionLegs: 'Odcinki trasy',
        genSectionOther: 'Inne',
        genDriver1: 'Kierowca 1',
        genDriver2: 'Kierowca 2',
        genRouteNr: 'Nr trasy',
        genDestination: 'Miejsca docelowe',
        genTruck: 'Ciągnik',
        genTrailer: 'Naczepa(y)',
        genDepartureDate: 'Data wyjazdu',
        genDepartureTime: 'Godzina wyjazdu',
        genReturnDate: 'Data powrotu',
        genReturnTime: 'Godzina powrotu',
        genDepartureOdometer: 'Licznik przy wyjeździe',
        genReturnOdometer: 'Licznik przy powrocie',
        genDistance: 'Dystans',
        genRef: (x) => `Nr referencyjny ${x}`,
        genFuelBefore: 'Paliwo przed trasą',
        genFuelAfter: 'Paliwo po trasie',
        genFuelConsumption: 'Spalanie (l/100 km)',
        genRefueled: 'Zatankowano łącznie',
        genFuelDate: (x) => `Tankowanie ${x} – data`,
        genFuelCity: (x) => `Tankowanie ${x} – miejsce`,
        genFuelOdometer: (x) => `Tankowanie ${x} – licznik`,
        genFuelValue: (x) => `Tankowanie ${x} – ilość`,
        genExpense: (x) => `Wydatek ${x}`,
        genStops: 'Postoje',
        genOther: 'Inne uwagi',
        genLeg: (x) => `Odcinek ${x}`,
        genAddLeg: 'Dodaj odcinek',
        legStartCity: 'Skąd',
        legStartData: 'Wyjazd (data i godzina)',
        legStartOdometer: 'Licznik – start',
        legBorderDate: 'Granica – data',
        legBorderPlace: 'Granica – miejsce',
        legStopCity: 'Dokąd',
        legStopData: 'Przyjazd (data i godzina)',
        legStopOdometer: 'Licznik – koniec',
        legDistance: 'Dystans',
        legCustomer: 'Ładunek',
        generatorSkippedLegs: (x) => `Szablon nie mieści wszystkich odcinków – ${x} nie zmieściło się w PDF. Połącz lub usuń część odcinków.`,
        noRecords: 'Brak wpisów.',
        browseRecords: 'Przeglądaj wpisy',
        editRecord: 'Edytuj',
        showMoreFields: 'Pokaż pozostałe pola',
        showLessFields: 'Ukryj dodatkowe pola',
        editSuccess: 'Wpis został zapisany.',
        logEditHeader: 'Edytuj czynność',
        dayEditHeader: 'Edytuj dzień pracy',
        financeEditHeader: 'Edytuj wydatek',
        loadEditHeader: 'Edytuj ładunek',
        sectionStart: 'Rozpoczęcie',
        sectionStop: 'Zakończenie',
        sectionLoading: 'Załadunek',
        sectionUnloading: 'Rozładunek',
        logsTitle: 'Czynności',
        activity: 'Czynność',
        country: 'Kraj',
        place: 'Miejsce',
        odometer: 'Licznik',
        notes: 'Notatki',
        daysTitle: 'Dni pracy',
        start: 'Rozpoczęcie',
        stop: 'Zakończenie',
        breakTime: 'Przerwa',
        secondDriver: '2. kierowca',
        financesTitle: 'Finanse',
        description: 'Pozycja',
        quantity: 'Ilość',
        unitPrice: 'Cena jedn.',
        amount: 'Kwota',
        foreignAmount: 'Kwota walutowa',
        payment: 'Płatność',
        loadsTitle: 'Ładunki',
        loadNr: 'Ładunek nr',
        loading: 'Załadunek',
        unloading: 'Rozładunek',
        notUnloaded: 'nierozładowany',
        sender: 'Nadawca',
        receiver: 'Odbiorca',
        reference: 'Numer referencyjny',
        vehicle: 'Pojazd',
        weight: 'Waga',
    },
};
