import { VehiclesInterface } from "@/types/text/VehiclesInterface";

// Teksty karty Pojazdy – odpowiednik front `assets/txt/vehicles.ts` (+ kilka etykiet mobilnych).
export const vehicles: VehiclesInterface = {
    en: {
        listTitle: 'Vehicles',
        trucksTab: 'Trucks',
        trailersTab: 'Trailers',
        company: 'Company',
        apiTrucksError: 'The trucks list could not be downloaded due to a network problem or the login session has expired.',
        apiTrailersError: 'The trailers list could not be downloaded due to a network problem or the login session has expired.',
        empty: 'No vehicles.',
        currentVehicle: 'current tour',
        truck: 'Truck',
        trailer: 'Trailer',
        registrationPlate: 'Registration plate',
        model: 'Brand/model',
        yearOfProduction: 'Year of Production',
        isLoadable: 'Loadable Truck',
        tankCapacity: 'Tank capacity',
        weight: 'Vehicle weight',
        weightDisp: 'Weight',
        techRev: 'Next Technical Review',
        insurance: 'Insurance validity',
        tacho: 'Next Tachograph Inspection',
        nextService: 'Next service at',
        notes: 'Additional information',
        yes: 'Yes',
        no: 'No',
        addVehicle: 'Add New Vehicle',
        addSuccess: 'A new vehicle has been added.',
        edit: 'Edit',
        editHeader: (x) => `Edit ${x}`,
        editSuccessInfo: 'The vehicle has been successfully edited.',
        noChanges: 'No changes to save.',
        showServices: 'Maintenance / services list',
        serviceHeader: (x) => `Services: ${x}`,
        serviceType: 'Type of Service',
        serviceAll: 'All',
        serviceMaintenance: 'Maintenance',
        serviceService: 'Service',
        serviceDate: 'Date',
        servicePlace: 'Place',
        serviceOdometer: 'Mileage',
        serviceEmpty: 'No entries.',
        search: 'Search',
        editServiceHeader: 'Edit entry',
        editLogLegend: 'Activity',
        editServiceSuccess: 'The details of the selected entrance have been edited successfully.',
    },
    pl: {
        listTitle: 'Pojazdy',
        trucksTab: 'Ciężarówki',
        trailersTab: 'Naczepy/przyczepy',
        company: 'Firma',
        apiTrucksError: 'Lista ciężarówek nie mogła zostać pobrana z powodu problemu z siecią lub sesja logowania wygasła.',
        apiTrailersError: 'Lista naczep/przyczep nie mogła zostać pobrana z powodu problemu z siecią lub sesja logowania wygasła.',
        empty: 'Brak pojazdów.',
        currentVehicle: 'bieżąca trasa',
        truck: 'Ciężarówka',
        trailer: 'Naczepa/Przyczepa',
        registrationPlate: 'Nr. Rejestracyjny',
        model: 'Marka/model',
        yearOfProduction: 'Rok produkcji',
        isLoadable: 'Pojazd ładowalny',
        tankCapacity: 'Pojemność zbiorników paliwa',
        weight: 'Waga pojazdu (pole G)',
        weightDisp: 'Waga pojazdu',
        techRev: 'Przegląd techniczny',
        insurance: 'Ubezpieczenie OC',
        tacho: 'Legalizacja tachografu',
        nextService: 'Następna obsługa serwisowa',
        notes: 'Dodatkowe informacje',
        yes: 'Tak',
        no: 'Nie',
        addVehicle: 'Dodaj nowy pojazd',
        addSuccess: 'Dodano nowy pojazd.',
        edit: 'Edytuj',
        editHeader: (x) => `Edytuj ${x}`,
        editSuccessInfo: 'Pojazd został pomyślnie edytowany.',
        noChanges: 'Brak zmian do zapisania.',
        showServices: 'Lista obsługi / serwisów',
        serviceHeader: (x) => `Serwisy: ${x}`,
        serviceType: 'Rodzaj serwisu',
        serviceAll: 'Wszystko',
        serviceMaintenance: 'Obsługa',
        serviceService: 'Serwis',
        serviceDate: 'Data',
        servicePlace: 'Miejsce',
        serviceOdometer: 'Przebieg',
        serviceEmpty: 'Brak wpisów.',
        search: 'Szukaj',
        editServiceHeader: 'Edytuj wpis',
        editLogLegend: 'Czynność',
        editServiceSuccess: 'Szczegóły wybranej pozycji zostały edytowane pomyślnie.',
    },
};
