export interface Entries {
    blockedDescription: string;
    dayStart: string;
    dayStop: string;
    dayExist: string;
    dayNotExist: string;
    addLog: string;
    addLogSuccess(x: string): string;
    crossBorder: string;
    crossBorderSwitchToAdd: string;
    crossBorderSwitchToChoose: string;
    border: string;
    crossBorderYouAre(x: string): string;
    dieselRefuel: string;
    adblueRefuel: string;
    addExpense: string;
    startedDayAction: string;
    startedDayActionCardInsert: string;
    finishedDayAction: string;
    finishedDayActionCardTakeOut: string;
    expenseItemDescription: string;
    expenseItemDescriptionHelper: string;
    expenseQuantity: string;
    expenseUnitPrice: string;
    expenseForeignCurrency: string;
    cash: string;
    paymentMethod: string;
    newPaymentLabel: string;
    paymentForeignCurrency: string;
    expenseAddAction: string;
    addedExpenseActionSuccess: string;
    loadingArrival: string;
    loadingArrivalAction: string;
    loadingArrivalSuccess: string;
    loadingCompleted: string;
    loadingCompletedAction: string;
    loadingCompletedSuccess: string;
    loadingSenderSwitchLabel: string;
    loadingPlace: string;
    loadingSender: string;
    loadingReceiver: string;
    loadedVehicle: string;
    vehicleDetailsNotFound: string;
    loadReference: string;
    loadDescription: string;
    loadWeight: string;
    loadQuantity: string;
    unloadingArrival: string;
    unloadingArrivalSuccess: string;
    unloadingArrivalAction: string;
    unloadingCompleted: string;
    unloadingCompletedAction: string;
    unloadingCompletedSuccess: string;
    unloadingLoadSelectLabel: string;
    chooseLoad: string;
    noLoadReceiver: string;
    attachTrailer: string;
    attachTrailerAction: string;
    attachTrailerSuccess: string;
    trailerNoValid: string;
    detachTrailer: string;
    detachTrailerAction: string;
    detachTrailerSuccess: string;
}

export interface HomeInterface {
    en: Entries;
    pl: Entries;
}