interface Entries {
    listTitle: string;
    noTours: string;
    apiError: string;
    tour: string;
    tours: string;
    na: string;
    // przełącznik kart
    tabUnaccounted: string;
    tabSettled: string;
    tabStats: string;
    // rozliczenia miesięczne
    settlementsTitle: string;
    noSettlements: string;
    month: string;
    viewRouteList: string;
    settledRoutesTitle: string;
    deleteSettlement: string;
    deleteSettlementConfirm: string;
    deleteSettlementSuccess: string;
    // statystyki
    statsNoData: string;
    statsTotal: string;
    statsByMonth: string;
    year: string;
    truck: string;
    distance: string;
    fuelUsage: string;
    salary: string;
    predicted: string;
    real: string;
    outgoings: string;
    sectionTime: string;
    sectionFuel: string;
    sectionLoads: string;
    sectionSalary: string;
    driveTime: string;
    workTime: string;
    onDuty: string;
    offDuty: string;
    fuel: string;
    before: string;
    after: string;
    burned: string;
    boardComputer: string;
    refueled: string;
    averageLoadWeight: string;
    numberOfLoads: string;
    rate: string;
    perKm: string;
    perHour: string;
    perDay: string;
    startNotes: string;
    stopNotes: string;
    showLogs: string;
    showDays: string;
    showFinances: string;
    showLoads: string;
    generate: string;
    generateSoon: string;
    noRecords: string;
    // przeglądanie wpisów (wspólna lista)
    browseRecords: string;
    editRecord: string;
    showMoreFields: string;
    showLessFields: string;
    editSuccess: string;
    logEditHeader: string;
    dayEditHeader: string;
    financeEditHeader: string;
    loadEditHeader: string;
    sectionStart: string;
    sectionStop: string;
    sectionLoading: string;
    sectionUnloading: string;
    // logs
    logsTitle: string;
    activity: string;
    country: string;
    place: string;
    odometer: string;
    notes: string;
    // days
    daysTitle: string;
    start: string;
    stop: string;
    breakTime: string;
    secondDriver: string;
    // finances
    financesTitle: string;
    description: string;
    quantity: string;
    unitPrice: string;
    amount: string;
    foreignAmount: string;
    payment: string;
    // loads
    loadsTitle: string;
    loadNr: string;
    loading: string;
    unloading: string;
    notUnloaded: string;
    sender: string;
    receiver: string;
    reference: string;
    vehicle: string;
    weight: string;
}

export interface ToursInterface {
    en: Entries;
    pl: Entries;
}
